# Generated by Django 6.0.1 on 2026-01-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique key for the setting (e.g. MAINTENANCE_MODE)', max_length=50, unique=True)),
                ('value', models.CharField(help_text='The value of the setting', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('value_type', models.CharField(choices=[('STRING', 'String'), ('INTEGER', 'Integer'), ('BOOLEAN', 'Boolean'), ('FLOAT', 'Float')], default='STRING', max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='If true, accessible by public API')),
            ],
        ),
    ]
